"""JAX implementation of selected SSMTool numerical kernels.

The MATLAB implementation in ``SSMTool/`` remains the reference. This
package ports low-level kernels first and documents differentiability status
for every public API.
"""

from ssmtoolpy.coefficients import (
    ConjugateOrdering,
    coeffs_conj2full,
    coeffs_conj2lex,
    coeffs_lex2revlex,
    coeffs_output,
    conjugate_flip,
    conjugate_ordering,
    number_of_multis,
)
from ssmtoolpy.dynamical_system import (
    FourierForcingTerm,
    PeriodicForcing,
    ResidualResult,
    evaluate_first_order_vector_field,
    evaluate_periodic_forcing,
    evaluate_polynomial_jacobian,
    evaluate_polynomial_terms,
    first_order_polynomial_terms_from_second_order,
    first_order_from_second_order_nonlinearity,
    first_order_nonlinearity,
    first_order_tensor_terms_from_second_order,
    first_order_terms_from_second_order,
    mechanical_binv_a,
    mechanical_a_matrix,
    mechanical_b_matrix,
    polynomial_degree,
    polynomial_input_dim,
    second_order_internal_force,
    second_order_internal_force_jacobian_x,
    second_order_internal_force_jacobian_xd,
    second_order_residual,
)
from ssmtoolpy.frc import (
    check_stability,
    compute_fixed_points_2d,
    compute_gamma,
    frc_ab,
    frc_jacobian,
    frc_psi,
    get_contour_xy,
)
from ssmtoolpy.manifold import (
    NonAutonomousCoefficientSeries,
    NonAutonomousResonanceData,
    NonAutonomousStructure,
    autonomous_resonant_terms,
    check_comp_type,
    check_ds_type,
    coeffs_composition,
    coeffs_mixed_terms,
    nonautonomous_conjugate_reduction,
    nonautonomous_resonant_terms,
    nonautonomous_struct_setup,
    nonautonomous_w1r0_plus_w0r1,
)
from ssmtoolpy.misc import (
    AutoReducedDynamicsData,
    OutputSummary,
    ProjectionData,
    auto_red_dyn,
    extract_output,
    nonlinear_projection_objective,
    project_to_ssm_linear,
    real_to_conjugate_state,
    reduced_to_full_traj,
    solve_invariance_equation,
    spblkdiag,
    squared_distance_to_point_ssm,
)
from ssmtoolpy.multi_index import (
    MultiIndexPolynomial,
    expand_multiindex,
    expand_multiindex_derivative,
    multi_addition,
    multi_index_2_ordering,
    multi_index_to_tensor,
    multi_nsumk,
    multi_subtraction,
    nsumk,
    sub2multiind,
    tensor_to_multi_index,
)
from ssmtoolpy.options import DSOptions, FRCOptions, FRSOptions, ManifoldOptions, matlab_style_options
from ssmtoolpy.reduction import NonAutonomousTerm, reduced_to_full, reduced_to_full_complex
from ssmtoolpy.tensor import expand_tensor, expand_tensor_derivative, khatri_rao_product

__all__ = [
    "MultiIndexPolynomial",
    "AutoReducedDynamicsData",
    "ConjugateOrdering",
    "DSOptions",
    "FRCOptions",
    "FRSOptions",
    "FourierForcingTerm",
    "ManifoldOptions",
    "NonAutonomousCoefficientSeries",
    "NonAutonomousTerm",
    "NonAutonomousResonanceData",
    "NonAutonomousStructure",
    "OutputSummary",
    "PeriodicForcing",
    "ProjectionData",
    "ResidualResult",
    "auto_red_dyn",
    "coeffs_conj2full",
    "coeffs_conj2lex",
    "coeffs_composition",
    "coeffs_lex2revlex",
    "coeffs_mixed_terms",
    "coeffs_output",
    "conjugate_flip",
    "conjugate_ordering",
    "autonomous_resonant_terms",
    "check_comp_type",
    "check_ds_type",
    "check_stability",
    "compute_fixed_points_2d",
    "compute_gamma",
    "extract_output",
    "evaluate_first_order_vector_field",
    "evaluate_periodic_forcing",
    "evaluate_polynomial_jacobian",
    "evaluate_polynomial_terms",
    "first_order_polynomial_terms_from_second_order",
    "expand_multiindex",
    "expand_multiindex_derivative",
    "expand_tensor",
    "expand_tensor_derivative",
    "frc_ab",
    "frc_jacobian",
    "frc_psi",
    "first_order_from_second_order_nonlinearity",
    "first_order_nonlinearity",
    "first_order_tensor_terms_from_second_order",
    "first_order_terms_from_second_order",
    "get_contour_xy",
    "khatri_rao_product",
    "mechanical_binv_a",
    "mechanical_a_matrix",
    "mechanical_b_matrix",
    "polynomial_degree",
    "polynomial_input_dim",
    "matlab_style_options",
    "multi_addition",
    "multi_index_2_ordering",
    "multi_index_to_tensor",
    "multi_nsumk",
    "multi_subtraction",
    "nonlinear_projection_objective",
    "nonautonomous_conjugate_reduction",
    "nonautonomous_resonant_terms",
    "nonautonomous_struct_setup",
    "nonautonomous_w1r0_plus_w0r1",
    "number_of_multis",
    "nsumk",
    "project_to_ssm_linear",
    "real_to_conjugate_state",
    "reduced_to_full",
    "reduced_to_full_complex",
    "reduced_to_full_traj",
    "second_order_internal_force",
    "second_order_internal_force_jacobian_x",
    "second_order_internal_force_jacobian_xd",
    "second_order_residual",
    "solve_invariance_equation",
    "spblkdiag",
    "squared_distance_to_point_ssm",
    "sub2multiind",
    "tensor_to_multi_index",
]
